name: ${project.artifactId}
main: com.gmail.nuclearcat1337.xpSystem.main.XPMain
version: ${project.version}
authors: [Mr_Little_Kitty, kh498]
depend: [Annihilation]
description: An Annihilation XP System
commands:
  MyXP:
    description: Shows the player's XP
  Shop:
    description: Opens the Kit Shop
  Convert:
    description: Opens the exchange shop
permissions: