name: ${project.artifactId}
main: com.gmail.nuclearcat1337.xpSystem.main.XPMain
version: ${project.version}
authors: [Mr_Little_Kitty, kh498]
depend: [Annihilation]
description: An Annihilation XP System
commands:
  MyXP:
    description: Shows the player's XP
  Achievements:
    aliases: [Ach]
    description: Shows how far a player have come in their kit achivements
  Shop:
    description: Opens the Kit Shop
permissions: