name: ${project.artifactId}
main: com.gmail.nuclearcat1337.vaultPlugin.VaultHook
version: ${project.version}
authors: [Mr_Little_Kitty, kh498]
depend: [Vault, Annihilation]
description: An Annihilation vault hook
commands:
permissions: