name: AnnihilationVault
main: com.gmail.nuclearcat1337.vaultPlugin.VaultHook
version: 1.1.0
authors: [Mr_Little_Kitty]
depend: [Vault, Annihilation]
description: An Annihilation vault hook
commands:
permissions: